spring.application.name=JPA_CRUD_Category

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=JPA_DB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

server.port=8080
server.servlet.context-path=/

app.upload-dir=C:/upload
app.page-size=5
